### ISSUE TITLE
mvn compilation

### ISSUE THREAD

**Issue by ilknuricke** [fiji/microscope-image-quality#3]
mvn command given here leads to an error on mac OS High Sierra 10.13.4
log4j:WARN No appenders could be found for logger (org.bushe.swing.event.EventService).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
objc[22426]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff8844ec90) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x15bed9cd8). One of the two will be used. Which one is undefined.

it generates the jar files if you use mvn install

**Comment by ctrueden** [comment]
@ilknuricke I think this is a machine-specific issue. I cannot reproduce with `mvn` on my High Sierra 10.13.6 system. What does your `mvn -v` say? Here's mine:
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T02:58:13-05:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_172, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.6", arch: "x86_64", family: "mac"
```

**Comment by ctrueden** [comment]
Closing due to lack of response. @ilknuricke If you still have problems, feel free to reopen and include the requested details above.
